# Generated by Django 5.2.13 on 2026-05-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_products_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
