# Generated by Django 5.2.13 on 2026-05-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
